version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../server/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - app

volumes:
  mongo-data:
