version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - web-network

  app:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - web-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - app
    networks:
      - web-network

volumes:
  mongo-data:

networks:
  web-network: